-- ============================================================================
-- Risk, Fraud, and Regulatory Intelligence Copilot
-- Step 7: Scheduled Automation Task & 13+ Automated Validation Tests
-- ============================================================================

USE DATABASE RISK_COPILOT;
USE SCHEMA APP;

-- 1. Unattended Hourly Triage Stored Procedure
CREATE OR REPLACE PROCEDURE RISK_COPILOT.APP.AUTO_TRIAGE(MAX_DRAFTS INT)
RETURNS VARIANT
LANGUAGE SQL
COMMENT = 'Unattended run: drafts STRs for high-risk alerts without a case (bounded per run) and logs LCR threshold events'
EXECUTE AS CALLER
AS
$$
DECLARE drafted ARRAY DEFAULT ARRAY_CONSTRUCT(); failed ARRAY DEFAULT ARRAY_CONSTRUCT(); r VARIANT; lcr_row VARIANT; aid STRING;
  c1 CURSOR FOR SELECT a.ALERT_ID FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a
    WHERE a.RISK_SCORE >= 60 AND NOT EXISTS (SELECT 1 FROM RISK_COPILOT.APP.CASES c WHERE c.ALERT_ID = a.ALERT_ID)
    ORDER BY a.RISK_SCORE DESC, a.ALERT_ID LIMIT 50;
  n INT DEFAULT 0;
BEGIN
  FOR rec IN c1 DO
    IF (n >= MAX_DRAFTS) THEN BREAK; END IF;
    aid := rec.ALERT_ID;
    BEGIN
      CALL RISK_COPILOT.APP.GENERATE_SAR_DRAFT(:aid) INTO :r;
      drafted := ARRAY_APPEND(drafted, OBJECT_CONSTRUCT('alert', aid, 'case', r:case_id, 'guardrail_passed', r:guardrail:passed));
    EXCEPTION WHEN OTHER THEN
      failed := ARRAY_APPEND(failed, OBJECT_CONSTRUCT('alert', aid, 'error', SQLERRM));
    END;
    n := n + 1;
  END FOR;
  SELECT OBJECT_CONSTRUCT('as_of', AS_OF_DATE, 'lcr_pct', LCR_PCT, 'status', LCR_STATUS, 'stress_s1', LCR_STRESS_S1_PCT)
    INTO :lcr_row FROM RISK_COPILOT.CURATED.DT_LCR_DAILY ORDER BY AS_OF_DATE DESC LIMIT 1;
  IF (lcr_row:status::STRING <> 'GREEN') THEN
    INSERT INTO RISK_COPILOT.APP.AUDIT_LOG (EVENT_TYPE, OBJECT_ID, DETAILS) SELECT 'LCR_THRESHOLD_EVENT', 'LCR', :lcr_row;
  END IF;
  INSERT INTO RISK_COPILOT.APP.AUDIT_LOG (EVENT_TYPE, OBJECT_ID, DETAILS)
    SELECT 'AUTO_TRIAGE_RUN', 'TASK', OBJECT_CONSTRUCT('drafted', :drafted, 'failed', :failed, 'lcr', :lcr_row);
  RETURN OBJECT_CONSTRUCT('drafted', drafted, 'failed', failed, 'lcr', lcr_row);
END;
$$;

-- 2. Snowflake Scheduled Task
CREATE OR REPLACE TASK RISK_COPILOT.APP.T_AUTO_TRIAGE
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 * * * * Asia/Kolkata'
  COMMENT = 'Hourly unattended fraud/AML triage + liquidity threshold monitoring'
  SUSPEND_TASK_AFTER_NUM_FAILURES = 3
  USER_TASK_TIMEOUT_MS = 1800000
AS CALL RISK_COPILOT.APP.AUTO_TRIAGE(3);

-- Resume the task
ALTER TASK RISK_COPILOT.APP.T_AUTO_TRIAGE RESUME;

-- 3. Automated Validation Suite View
CREATE OR REPLACE VIEW RISK_COPILOT.APP.V_VALIDATION_TESTS AS
WITH truth AS (SELECT s.SCENARIO, a.ALERT_ID, a.TYPOLOGY FROM RISK_COPILOT.RAW.SYNTH_SCENARIOS s LEFT JOIN RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a ON a.ACCOUNT_ID = s.ACCOUNT_ID),
lcr AS (SELECT * FROM RISK_COPILOT.CURATED.DT_LCR_DAILY)
SELECT 'DETECTION: mule recall' TEST, '12/12' EXPECTED, (SELECT COUNT_IF(TYPOLOGY='MONEY_MULE')||'/'||COUNT(*) FROM truth WHERE SCENARIO='MULE') ACTUAL
UNION ALL SELECT 'DETECTION: structuring recall', '7/7', (SELECT COUNT_IF(TYPOLOGY='AML_LAYERING')||'/'||COUNT(*) FROM truth WHERE SCENARIO='STRUCTURING')
UNION ALL SELECT 'DETECTION: round-trip recall', '6/6', (SELECT COUNT_IF(TYPOLOGY='AML_LAYERING')||'/'||COUNT(*) FROM truth WHERE SCENARIO='ROUND_TRIP')
UNION ALL SELECT 'DETECTION: false positives on clean accounts', '0', (SELECT COUNT(*)::STRING FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a WHERE a.ACCOUNT_ID NOT IN (SELECT ACCOUNT_ID FROM RISK_COPILOT.RAW.SYNTH_SCENARIOS))
UNION ALL SELECT 'EXPLAINABILITY: every red flag maps to an existing policy section', '0 unmapped',
  (SELECT COUNT(*)||' unmapped' FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a, LATERAL FLATTEN(a.RED_FLAGS) f
    WHERE NOT EXISTS (SELECT 1 FROM RISK_COPILOT.RAW.POLICY_DOCS p WHERE STARTSWITH(p.SECTION, REGEXP_REPLACE(f.value:policy::STRING, '\\([a-z]\\)$', ''))))
UNION ALL SELECT 'DATA: transactions reference valid accounts', '0 orphans',
  (SELECT COUNT(*)||' orphans' FROM RISK_COPILOT.RAW.TRANSACTIONS t WHERE NOT EXISTS (SELECT 1 FROM RISK_COPILOT.RAW.ACCOUNTS a WHERE a.ACCOUNT_ID=t.ACCOUNT_ID))
UNION ALL SELECT 'DATA: no duplicate transaction IDs', '0', (SELECT (COUNT(*)-COUNT(DISTINCT TXN_ID))::STRING FROM RISK_COPILOT.RAW.TRANSACTIONS)
UNION ALL SELECT 'CREDIT: SMA class consistent with DPD', '0 mismatches',
  (SELECT COUNT(*)||' mismatches' FROM RISK_COPILOT.CURATED.DT_LOAN_EWS WHERE (ASSET_CLASS='SMA-0' AND DPD NOT BETWEEN 1 AND 30) OR (ASSET_CLASS='SMA-1' AND DPD NOT BETWEEN 31 AND 60) OR (ASSET_CLASS='SMA-2' AND DPD NOT BETWEEN 61 AND 90) OR (ASSET_CLASS='NPA' AND DPD <= 90) OR (ASSET_CLASS='STANDARD' AND DPD<>0))
UNION ALL SELECT 'LIQUIDITY: Level 2 share <= 40% of HQLA', '0 breaches',
  (SELECT COUNT(*)||' breaches' FROM lcr WHERE (HQLA_STOCK - L1_HQLA) > 0.4*HQLA_STOCK + 1)
UNION ALL SELECT 'LIQUIDITY: status consistent with LCR thresholds', '0 mismatches',
  (SELECT COUNT(*)||' mismatches' FROM lcr WHERE LCR_STATUS <> CASE WHEN LCR_PCT<100 THEN 'REGULATORY_BREACH' WHEN LCR_PCT<110 THEN 'RED_CFP_TRIGGER' WHEN LCR_PCT<115 THEN 'AMBER_ALCO' ELSE 'GREEN' END)
UNION ALL SELECT 'GUARDRAIL: fabricated clauses are caught', '["Section 45-IA","[AML-POL 9.9]"]',
  RISK_COPILOT.APP.VALIDATE_CITATIONS('See Section 45-IA and [AML-POL 9.9] and [AML-POL 4.2(c)]', ARRAY_CONSTRUCT(), ARRAY_CONSTRUCT('AML-POL 4.2 Money Mule Red Flags'), '')::STRING
UNION ALL SELECT 'GUARDRAIL: grounded clauses pass', '[]',
  RISK_COPILOT.APP.VALIDATE_CITATIONS('Per [AML-POL 4.2(a)] and [AML-POL 6.1]', ARRAY_CONSTRUCT('[AML-POL 4.2]'), ARRAY_CONSTRUCT('AML-POL 4.2 Money Mule Red Flags','AML-POL 6.1 STR Filing Timeline'), '')::STRING
UNION ALL SELECT 'GOVERNANCE: every case requires human review', '0 without', (SELECT COUNT_IF(GUARDRAIL_RESULT:human_review_required::BOOLEAN IS DISTINCT FROM TRUE)||' without' FROM RISK_COPILOT.APP.CASES);

-- 4. Validation Results View
CREATE OR REPLACE VIEW RISK_COPILOT.APP.V_VALIDATION_RESULTS AS
SELECT TEST, EXPECTED, ACTUAL,
  IFF(EXPECTED = ACTUAL OR (TRY_PARSE_JSON(EXPECTED) IS NOT NULL AND ARRAY_SORT(TRY_PARSE_JSON(EXPECTED)::ARRAY) = ARRAY_SORT(TRY_PARSE_JSON(ACTUAL)::ARRAY)), 'PASS', 'FAIL') AS RESULT
FROM RISK_COPILOT.APP.V_VALIDATION_TESTS;
