-- ============================================================================
-- Risk, Fraud & Regulatory Intelligence Copilot
-- Step 8: Continuous Evidence + CoCo/MCP Integration Layer
--
-- Designed to sit ON TOP of the existing Steps 1-7.
-- Existing source of truth:
--   RISK_COPILOT.CURATED.DT_FRAUD_ALERTS
--   RISK_COPILOT.RAW.TRANSACTIONS
--   RISK_COPILOT.RAW.POLICY_DOCS
-- ============================================================================

USE DATABASE RISK_COPILOT;

CREATE SCHEMA IF NOT EXISTS EVIDENCE;
CREATE SCHEMA IF NOT EXISTS APP;

-- Optional append-only stream: useful for demonstrating "new input arrived".
CREATE OR REPLACE STREAM EVIDENCE.TRANSACTION_CHANGE_STREAM
  ON TABLE RAW.TRANSACTIONS
  APPEND_ONLY = TRUE;

CREATE TABLE IF NOT EXISTS EVIDENCE.RISK_FINDINGS (
    FINDING_ID STRING DEFAULT 'FND-' || UUID_STRING(),
    ALERT_ID STRING NOT NULL,
    ACCOUNT_ID STRING,
    CUSTOMER_ID STRING,
    FINDING_TYPE STRING,
    SEVERITY STRING,
    RISK_SCORE NUMBER(5,2),
    FINDING_STATUS STRING DEFAULT 'OPEN',
    SUMMARY STRING,
    PRIMARY_POLICY_ID STRING,
    PRIMARY_REGULATION_ID STRING,
    EVIDENCE_COUNT NUMBER DEFAULT 0,
    CONFIDENCE NUMBER(5,2),
    MODEL_VERSION STRING DEFAULT 'RULE_ENGINE_V1',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS EVIDENCE.RISK_EVIDENCE (
    EVIDENCE_ID STRING DEFAULT 'EVD-' || UUID_STRING(),
    FINDING_ID STRING,
    ALERT_ID STRING,
    ACCOUNT_ID STRING,
    CUSTOMER_ID STRING,
    EVIDENCE_TYPE STRING,
    SOURCE_OBJECT STRING,
    SOURCE_RECORD_ID STRING,
    OBSERVED_VALUE VARIANT,
    EXPECTED_VALUE VARIANT,
    EVIDENCE_TEXT STRING,
    POLICY_ID STRING,
    REGULATION_ID STRING,
    RULE_ID STRING,
    CONFIDENCE NUMBER(5,2),
    EVENT_TS TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY STRING DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS EVIDENCE.INVESTIGATION_CASES (
    CASE_ID STRING DEFAULT 'CASE-' || UUID_STRING(),
    FINDING_ID STRING,
    ALERT_ID STRING,
    ACCOUNT_ID STRING,
    CUSTOMER_ID STRING,
    CASE_TYPE STRING,
    PRIORITY STRING,
    STATUS STRING DEFAULT 'OPEN',
    SUMMARY STRING,
    EVIDENCE_COUNT NUMBER,
    CREATED_BY STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS EVIDENCE.AUDIT_ACTIONS (
    ACTION_ID STRING DEFAULT 'ACT-' || UUID_STRING(),
    CASE_ID STRING,
    FINDING_ID STRING,
    ACTION_TYPE STRING,
    TARGET_SYSTEM STRING,
    REQUESTED_BY STRING,
    REQUESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS STRING,
    RESULT VARIANT,
    ERROR_MESSAGE STRING
);

-- Continuous materialization:
-- DT_FRAUD_ALERTS is the existing governed fraud signal layer.
CREATE OR REPLACE TASK EVIDENCE.T_BUILD_RISK_FINDINGS
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
  SUSPEND_TASK_AFTER_NUM_FAILURES = 3
AS
MERGE INTO EVIDENCE.RISK_FINDINGS tgt
USING (
  SELECT
    a.ALERT_ID,
    a.ACCOUNT_ID,
    a.CUSTOMER_ID,
    a.TYPOLOGY AS FINDING_TYPE,
    CASE
      WHEN a.RISK_SCORE >= 80 THEN 'CRITICAL'
      WHEN a.RISK_SCORE >= 60 THEN 'HIGH'
      WHEN a.RISK_SCORE >= 35 THEN 'MEDIUM'
      ELSE 'LOW'
    END AS SEVERITY,
    a.RISK_SCORE,
    'Potential ' || a.TYPOLOGY || ' risk detected for account ' ||
      a.ACCOUNT_ID || '. Red flags: ' ||
      ARRAY_TO_STRING(a.FLAG_NAMES, ', ') AS SUMMARY,
    ARRAY_SIZE(a.RED_FLAGS) AS EVIDENCE_COUNT,
    LEAST(99, 70 + ARRAY_SIZE(a.RED_FLAGS) * 5) AS CONFIDENCE,
    a.SIGNAL_AS_OF AS EVENT_TS
  FROM CURATED.DT_FRAUD_ALERTS a
  WHERE a.RISK_SCORE >= 35
) src
ON tgt.ALERT_ID = src.ALERT_ID
WHEN MATCHED THEN UPDATE SET
  tgt.ACCOUNT_ID = src.ACCOUNT_ID,
  tgt.CUSTOMER_ID = src.CUSTOMER_ID,
  tgt.FINDING_TYPE = src.FINDING_TYPE,
  tgt.SEVERITY = src.SEVERITY,
  tgt.RISK_SCORE = src.RISK_SCORE,
  tgt.SUMMARY = src.SUMMARY,
  tgt.EVIDENCE_COUNT = src.EVIDENCE_COUNT,
  tgt.CONFIDENCE = src.CONFIDENCE,
  tgt.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (ALERT_ID,ACCOUNT_ID,CUSTOMER_ID,FINDING_TYPE,SEVERITY,RISK_SCORE,
   SUMMARY,EVIDENCE_COUNT,CONFIDENCE)
VALUES
  (src.ALERT_ID,src.ACCOUNT_ID,src.CUSTOMER_ID,src.FINDING_TYPE,src.SEVERITY,
   src.RISK_SCORE,src.SUMMARY,src.EVIDENCE_COUNT,src.CONFIDENCE);

CREATE OR REPLACE TASK EVIDENCE.T_BUILD_EVIDENCE
  WAREHOUSE = COMPUTE_WH
  AFTER EVIDENCE.T_BUILD_RISK_FINDINGS
AS
INSERT INTO EVIDENCE.RISK_EVIDENCE
(
  FINDING_ID, ALERT_ID, ACCOUNT_ID, CUSTOMER_ID,
  EVIDENCE_TYPE, SOURCE_OBJECT, SOURCE_RECORD_ID,
  OBSERVED_VALUE, EVIDENCE_TEXT, POLICY_ID, RULE_ID,
  CONFIDENCE, EVENT_TS
)
SELECT
  f.FINDING_ID,
  a.ALERT_ID,
  a.ACCOUNT_ID,
  a.CUSTOMER_ID,
  x.value:flag::STRING,
  'RISK_COPILOT.CURATED.DT_FRAUD_ALERTS',
  a.ALERT_ID,
  x.value,
  x.value:evidence::STRING,
  x.value:policy::STRING,
  x.value:flag::STRING,
  f.CONFIDENCE,
  a.SIGNAL_AS_OF
FROM CURATED.DT_FRAUD_ALERTS a
JOIN EVIDENCE.RISK_FINDINGS f
  ON f.ALERT_ID = a.ALERT_ID,
LATERAL FLATTEN(input => a.RED_FLAGS) x
WHERE NOT EXISTS (
  SELECT 1
  FROM EVIDENCE.RISK_EVIDENCE e
  WHERE e.FINDING_ID = f.FINDING_ID
    AND e.EVIDENCE_TYPE = x.value:flag::STRING
);

ALTER TASK EVIDENCE.T_BUILD_RISK_FINDINGS RESUME;
ALTER TASK EVIDENCE.T_BUILD_EVIDENCE RESUME;

CREATE OR REPLACE VIEW CURATED.V_RISK_COPILOT_FINDINGS AS
SELECT FINDING_ID, ALERT_ID, ACCOUNT_ID, CUSTOMER_ID, FINDING_TYPE,
       SEVERITY, RISK_SCORE, FINDING_STATUS, SUMMARY,
       PRIMARY_POLICY_ID, PRIMARY_REGULATION_ID, EVIDENCE_COUNT,
       CONFIDENCE, MODEL_VERSION, CREATED_AT, UPDATED_AT
FROM EVIDENCE.RISK_FINDINGS;

CREATE OR REPLACE VIEW CURATED.V_RISK_COPILOT_EVIDENCE AS
SELECT FINDING_ID, ALERT_ID, ACCOUNT_ID, CUSTOMER_ID, EVIDENCE_ID,
       EVIDENCE_TYPE, SOURCE_OBJECT, SOURCE_RECORD_ID, EVIDENCE_TEXT,
       POLICY_ID, REGULATION_ID, RULE_ID, CONFIDENCE, EVENT_TS
FROM EVIDENCE.RISK_EVIDENCE;

CREATE OR REPLACE VIEW CURATED.V_RISK_CASE_SUMMARY AS
SELECT c.CASE_ID,c.FINDING_ID,c.ALERT_ID,c.ACCOUNT_ID,c.CUSTOMER_ID,
       c.CASE_TYPE,c.PRIORITY,c.STATUS,c.SUMMARY,c.EVIDENCE_COUNT,
       c.CREATED_BY,c.CREATED_AT,f.RISK_SCORE,f.SEVERITY,f.FINDING_TYPE
FROM EVIDENCE.INVESTIGATION_CASES c
LEFT JOIN EVIDENCE.RISK_FINDINGS f ON f.FINDING_ID=c.FINDING_ID;

-- Quick validation
SELECT 'RISK_FINDINGS' AS CHECK_NAME, COUNT(*) AS VALUE FROM EVIDENCE.RISK_FINDINGS
UNION ALL SELECT 'RISK_EVIDENCE', COUNT(*) FROM EVIDENCE.RISK_EVIDENCE;
