USE DATABASE RISK_COPILOT;

CREATE OR REPLACE PROCEDURE APP.CREATE_INVESTIGATION_CASE(
  P_FINDING_ID STRING, P_PRIORITY STRING, P_SUMMARY STRING
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  V_CASE_ID STRING;
  V_ALERT_ID STRING;
  V_ACCOUNT_ID STRING;
  V_CUSTOMER_ID STRING;
  V_COUNT NUMBER;
BEGIN
  IF (UPPER(P_PRIORITY) NOT IN ('LOW','MEDIUM','HIGH','CRITICAL')) THEN
    RETURN OBJECT_CONSTRUCT('status','ERROR','message','INVALID_PRIORITY');
  END IF;

  SELECT ALERT_ID, ACCOUNT_ID, CUSTOMER_ID
  INTO :V_ALERT_ID, :V_ACCOUNT_ID, :V_CUSTOMER_ID
  FROM EVIDENCE.RISK_FINDINGS
  WHERE FINDING_ID = :P_FINDING_ID
  LIMIT 1;

  IF (V_ALERT_ID IS NULL) THEN
    RETURN OBJECT_CONSTRUCT('status','ERROR','message','FINDING_NOT_FOUND',
                            'finding_id',P_FINDING_ID);
  END IF;

  SELECT COUNT(*) INTO :V_COUNT
  FROM EVIDENCE.RISK_EVIDENCE
  WHERE FINDING_ID = :P_FINDING_ID;

  V_CASE_ID := 'CASE-' || UUID_STRING();

  INSERT INTO EVIDENCE.INVESTIGATION_CASES
    (CASE_ID,FINDING_ID,ALERT_ID,ACCOUNT_ID,CUSTOMER_ID,CASE_TYPE,
     PRIORITY,SUMMARY,EVIDENCE_COUNT,CREATED_BY)
  VALUES
    (:V_CASE_ID,:P_FINDING_ID,:V_ALERT_ID,:V_ACCOUNT_ID,:V_CUSTOMER_ID,
     'FRAUD_RISK_INVESTIGATION',UPPER(:P_PRIORITY),:P_SUMMARY,:V_COUNT,CURRENT_USER());

  INSERT INTO EVIDENCE.AUDIT_ACTIONS
    (CASE_ID,FINDING_ID,ACTION_TYPE,TARGET_SYSTEM,REQUESTED_BY,STATUS,RESULT)
  VALUES
    (:V_CASE_ID,:P_FINDING_ID,'CREATE_INVESTIGATION','SNOWFLAKE',
     CURRENT_USER(),'SUCCESS',
     OBJECT_CONSTRUCT('case_id',:V_CASE_ID,'evidence_count',:V_COUNT));

  RETURN OBJECT_CONSTRUCT('status','SUCCESS','case_id',V_CASE_ID,
                          'finding_id',P_FINDING_ID,'evidence_count',V_COUNT);
END;
$$;

CREATE OR REPLACE PROCEDURE APP.GENERATE_AUDIT_PACKAGE(P_FINDING_ID STRING)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE V_FINDING VARIANT; V_EVIDENCE VARIANT;
BEGIN
  SELECT OBJECT_CONSTRUCT(
    'finding_id',FINDING_ID,'alert_id',ALERT_ID,'account_id',ACCOUNT_ID,
    'customer_id',CUSTOMER_ID,'finding_type',FINDING_TYPE,'severity',SEVERITY,
    'risk_score',RISK_SCORE,'status',FINDING_STATUS,'summary',SUMMARY,
    'confidence',CONFIDENCE,'model_version',MODEL_VERSION)
  INTO :V_FINDING
  FROM EVIDENCE.RISK_FINDINGS
  WHERE FINDING_ID=P_FINDING_ID;

  SELECT COALESCE(ARRAY_AGG(OBJECT_CONSTRUCT(
    'evidence_id',EVIDENCE_ID,'type',EVIDENCE_TYPE,'text',EVIDENCE_TEXT,
    'policy_id',POLICY_ID,'regulation_id',REGULATION_ID,'rule_id',RULE_ID,
    'source_record_id',SOURCE_RECORD_ID,'event_ts',EVENT_TS)),ARRAY_CONSTRUCT())
  INTO :V_EVIDENCE
  FROM EVIDENCE.RISK_EVIDENCE
  WHERE FINDING_ID=P_FINDING_ID;

  RETURN OBJECT_CONSTRUCT(
    'package_type','AUDIT_READY_RISK_FINDING',
    'generated_at',CURRENT_TIMESTAMP(),
    'finding',V_FINDING,'evidence',V_EVIDENCE);
END;
$$;
