USE DATABASE RISK_COPILOT;

SELECT 'HIGH_RISK_WITHOUT_EVIDENCE' AS CHECK_NAME, COUNT(*) AS VALUE
FROM EVIDENCE.RISK_FINDINGS f
LEFT JOIN EVIDENCE.RISK_EVIDENCE e ON e.FINDING_ID=f.FINDING_ID
WHERE f.RISK_SCORE >= 60
GROUP BY f.FINDING_ID
HAVING COUNT(e.EVIDENCE_ID)=0;

SELECT 'DUPLICATE_EVIDENCE' AS CHECK_NAME, COUNT(*) AS VALUE
FROM (
  SELECT FINDING_ID,EVIDENCE_TYPE,COUNT(*) C
  FROM EVIDENCE.RISK_EVIDENCE
  GROUP BY 1,2
  HAVING COUNT(*)>1
);

SELECT * FROM CURATED.V_RISK_COPILOT_FINDINGS
ORDER BY CREATED_AT DESC LIMIT 20;

SELECT * FROM CURATED.V_RISK_COPILOT_EVIDENCE
ORDER BY EVENT_TS DESC LIMIT 50;
